import {
  AlertCircle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  User,
  X,
  Upload,
  Mic,
  Video,
  Link as LinkIcon,
  Paperclip,
  BarChart3,
  Music,
  Globe,
  Book,
} from "lucide-react";

// Import Simple Icons for brands
import {
  SiGithub,
  SiYoutube,
  SiGoogle,
  SiX,
} from "@icons-pack/react-simple-icons";

export type Icon = LucideIcon;

export const Icons = {
  logo: Book,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  page: File,
  media: Image,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  document: FileText,
  ellipsis: MoreVertical,
  creditCard: CreditCard,
  cmd: Command,
  github: SiGithub,
  upload: Upload,
  mic: Mic,
  video: Video,
  link: LinkIcon,
  attachment: Paperclip,
  chart: BarChart3,
  audio: Music,
  youtube: SiYoutube,
  web: Globe,
  google: SiGoogle,
  twitter: SiX,
};
